import 'package:connectivity_plus/connectivity_plus.dart';

class MainController{

  String token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaWJyYXJ5V0RBQGdtYWlsLmNvbSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cDovL3dkYS5ob3B0by5vcmc6ODA2Ni9hcGkvYXV0aGVudGljYXRpb24vbG9naW4iLCJleHAiOjE2NzU2MjI4Nzl9.d_ylPbrax69eEoFcD4PoQxQI562bf5PXj9YsADK1ZRo";
  static late ConnectivityResult result;


}