import 'package:connectivity_plus/connectivity_plus.dart';

class MainController{

  String token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaWJyYXJ5V0RBQGdtYWlsLmNvbSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cDovL3dkYS5ob3B0by5vcmc6ODA2Ni9hcGkvYXV0aGVudGljYXRpb24vbG9naW4iLCJleHAiOjE2NzU2Mzg4MzF9.pIpr8vvBjxHLhmikO5zckntG7aXUFMnlkhRcEAmOsFI";
  static late ConnectivityResult result;


}